
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Projects from '../component/Projects'
import styles from '../styles/Home.module.css'
import Page from './Projects'


 function Home({data}) {


    
  return (
    <div className={styles.container}>
      <Head>
        <title>Jith Stephen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{backgroundColor:"yellow"}} >

        <div style={{display:"flex" ,gap:"5px",justifyContent:"space-around ",backgroundColor:"white" }}>

          <div style={{display:"flex" ,flexDirection:"column", justifyContent:"center", alignItems:"center" ,width:"30%"}}>
          <div style={{display:"flex" ,flexDirection:"column", justifyContent:"center", alignItems:"center",backgroundColor:"white" ,marginBottom:"20px"}}>
           <Image 
             src={data.avatar_url}
             alt=""
             width={100}
             height={100}
             style={{borderRadius:"50%"}}
           />

           <h2>{data.name}</h2>
           <Link href={data.html_url}>{data.login}</Link>

           <p>{data.bio}</p>
           <div style={{display:"flex", gap:"30px"}}>
            <button style={{padding:"15px" ,width:"50%"}}>  <Link href={"https://drive.google.com/file/d/1RpHZgTgGbC4Y5xsCedBbqq_YIL-hFUYh/view?usp=sharing"}>Resume</Link> </button>
            <button  style={{padding:"15px" ,width:"50%"}}>  <Link href={data.html_url}>Follow</Link> </button>
            
            


          
           
           </div>

           </div>
            <div style={{display:"flex" ,flexDirection:"column", justifyContent:"center", alignItems:"center",backgroundColor:"white",marginBottom:"20px" ,width:"full" }}>

            <h4>{data.bio}</h4>

            
           </div>
           <div style={{display:"flex" ,flexDirection:"column", justifyContent:"center", alignItems:"center",backgroundColor:"white",marginBottom:"20px",width:"full",padding:"100px"}}>

           <p>Masai School</p>
           <p> holly cross college </p>
           <p>st .jsoseph H s sechool </p>
           

           

            
           </div>


          </div>


          <div>
          
            <Projects/>

          </div>

        </div>

       
      </main>

     
    </div>
  )
}

export async function getStaticProps(context) {
  const res= await fetch(`https://api.github.com/users/jithstephen13`)
  const data= await res.json()
  return {
    props: {data}, 
  }

 
}

export default Home
