import React from 'react';

const Projects = ({data}) => {
 console.log
 

  
 let item= [
  {
    id: 569159649,
    node_id: 'R_kgDOIeyv4Q',
    name: 'jithstephen13.github.io',
    full_name: 'jithstephen13/jithstephen13.github.io',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io',
    forks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/deployments',
    created_at: '2022-11-22T08:02:12Z',
    updated_at: '2022-11-22T08:11:30Z',
    pushed_at: '2022-12-04T06:52:32Z',
    git_url: 'git://github.com/jithstephen13/jithstephen13.github.io.git',
    ssh_url: 'git@github.com:jithstephen13/jithstephen13.github.io.git',
    clone_url: 'https://github.com/jithstephen13/jithstephen13.github.io.git',
    svn_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    homepage: null,
    size: 7543,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'gh-pages',
    score: 1
  },
  {
    id: 571677469,
    node_id: 'R_kgDOIhMbHQ',
    name: 'abcdefg',
    full_name: 'jithstephen13/abcdefg',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/abcdefg',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/abcdefg',
    forks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/abcdefg/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/abcdefg/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/abcdefg/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/abcdefg/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/abcdefg/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/abcdefg/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/abcdefg/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/abcdefg/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/abcdefg/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/abcdefg/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/abcdefg/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/abcdefg/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/abcdefg/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/abcdefg/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/abcdefg/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/deployments',
    created_at: '2022-11-28T16:41:21Z',
    updated_at: '2022-12-03T12:39:55Z',
    pushed_at: '2022-12-03T12:40:41Z',
    git_url: 'git://github.com/jithstephen13/abcdefg.git',
    ssh_url: 'git@github.com:jithstephen13/abcdefg.git',
    clone_url: 'https://github.com/jithstephen13/abcdefg.git',
    svn_url: 'https://github.com/jithstephen13/abcdefg',
    homepage: null,
    size: 494,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    score: 1
  },
  {
    id: 569159649,
    node_id: 'R_kgDOIeyv4Q',
    name: 'jithstephen13.github.io',
    full_name: 'jithstephen13/jithstephen13.github.io',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io',
    forks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/deployments',
    created_at: '2022-11-22T08:02:12Z',
    updated_at: '2022-11-22T08:11:30Z',
    pushed_at: '2022-12-04T06:52:32Z',
    git_url: 'git://github.com/jithstephen13/jithstephen13.github.io.git',
    ssh_url: 'git@github.com:jithstephen13/jithstephen13.github.io.git',
    clone_url: 'https://github.com/jithstephen13/jithstephen13.github.io.git',
    svn_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    homepage: null,
    size: 7543,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'gh-pages',
    score: 1
  },
  {
    id: 571677469,
    node_id: 'R_kgDOIhMbHQ',
    name: 'abcdefg',
    full_name: 'jithstephen13/abcdefg',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/abcdefg',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/abcdefg',
    forks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/abcdefg/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/abcdefg/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/abcdefg/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/abcdefg/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/abcdefg/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/abcdefg/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/abcdefg/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/abcdefg/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/abcdefg/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/abcdefg/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/abcdefg/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/abcdefg/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/abcdefg/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/abcdefg/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/abcdefg/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/deployments',
    created_at: '2022-11-28T16:41:21Z',
    updated_at: '2022-12-03T12:39:55Z',
    pushed_at: '2022-12-03T12:40:41Z',
    git_url: 'git://github.com/jithstephen13/abcdefg.git',
    ssh_url: 'git@github.com:jithstephen13/abcdefg.git',
    clone_url: 'https://github.com/jithstephen13/abcdefg.git',
    svn_url: 'https://github.com/jithstephen13/abcdefg',
    homepage: null,
    size: 494,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    score: 1
  },
  {
    id: 569159649,
    node_id: 'R_kgDOIeyv4Q',
    name: 'jithstephen13.github.io',
    full_name: 'jithstephen13/jithstephen13.github.io',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io',
    forks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/jithstephen13.github.io/deployments',
    created_at: '2022-11-22T08:02:12Z',
    updated_at: '2022-11-22T08:11:30Z',
    pushed_at: '2022-12-04T06:52:32Z',
    git_url: 'git://github.com/jithstephen13/jithstephen13.github.io.git',
    ssh_url: 'git@github.com:jithstephen13/jithstephen13.github.io.git',
    clone_url: 'https://github.com/jithstephen13/jithstephen13.github.io.git',
    svn_url: 'https://github.com/jithstephen13/jithstephen13.github.io',
    homepage: null,
    size: 7543,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'gh-pages',
    score: 1
  },
  {
    id: 571677469,
    node_id: 'R_kgDOIhMbHQ',
    name: 'abcdefg',
    full_name: 'jithstephen13/abcdefg',
    private: false,
    owner: [Object],
    html_url: 'https://github.com/jithstephen13/abcdefg',
    description: null,
    fork: false,
    url: 'https://api.github.com/repos/jithstephen13/abcdefg',
    forks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/forks',
    keys_url: 'https://api.github.com/repos/jithstephen13/abcdefg/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/jithstephen13/abcdefg/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/jithstephen13/abcdefg/teams',
    hooks_url: 'https://api.github.com/repos/jithstephen13/abcdefg/hooks',
    issue_events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/events{/number}',
    events_url: 'https://api.github.com/repos/jithstephen13/abcdefg/events',
    assignees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/assignees{/user}',
    branches_url: 'https://api.github.com/repos/jithstephen13/abcdefg/branches{/branch}',
    tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/tags',
    blobs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/jithstephen13/abcdefg/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/jithstephen13/abcdefg/languages',
    stargazers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/stargazers',
    contributors_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contributors',
    subscribers_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscribers',
    subscription_url: 'https://api.github.com/repos/jithstephen13/abcdefg/subscription',
    commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/jithstephen13/abcdefg/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/jithstephen13/abcdefg/contents/{+path}',
    compare_url: 'https://api.github.com/repos/jithstephen13/abcdefg/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/jithstephen13/abcdefg/merges',
    archive_url: 'https://api.github.com/repos/jithstephen13/abcdefg/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/jithstephen13/abcdefg/downloads',
    issues_url: 'https://api.github.com/repos/jithstephen13/abcdefg/issues{/number}',
    pulls_url: 'https://api.github.com/repos/jithstephen13/abcdefg/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/jithstephen13/abcdefg/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/jithstephen13/abcdefg/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/jithstephen13/abcdefg/labels{/name}',
    releases_url: 'https://api.github.com/repos/jithstephen13/abcdefg/releases{/id}',
    deployments_url: 'https://api.github.com/repos/jithstephen13/abcdefg/deployments',
    created_at: '2022-11-28T16:41:21Z',
    updated_at: '2022-12-03T12:39:55Z',
    pushed_at: '2022-12-03T12:40:41Z',
    git_url: 'git://github.com/jithstephen13/abcdefg.git',
    ssh_url: 'git@github.com:jithstephen13/abcdefg.git',
    clone_url: 'https://github.com/jithstephen13/abcdefg.git',
    svn_url: 'https://github.com/jithstephen13/abcdefg',
    homepage: null,
    size: 494,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'master',
    score: 1
  },
  
]
    
      const HandleClik=()=>{

      }
    
    return (
      
        <div style={{textAlign :"center"}}>
           <h1>Projectes</h1>
           <div  style={{textAlign :"center" ,display:"grid" , gridTemplateColumns:"50% 50%"}}>
          {
            item.map((item)=>{
              return (
                <div key={Math.random() }  style={{ display:"flex", justifyContent:"space-around", alignItems:"baseline", padding:"30px"}}
                 onClick={HandleClik}
                >

                  <div>
                    <h2>{item.name}</h2>

                    <p>{item.description}</p>
                    <div  style={{ display:"flex", margin:"auto"}}> 
                      <h4>Like: {item .score}</h4>
                      <h4>forks: {item.forks_count}</h4>

                        </div>

                  </div>
                  <div>
                    <h2 style={{marginBottom:"-30px"}}>{item.language}</h2>

                  </div>



                </div>
              )
            })
          }
</div>

            
        </div>
    );
};

export async function getServerSideProps(context) {
  const res= await fetch(`https://api.github.com/search/repositories?q=user:jithstephen13+fork:true&sort=updated&per_page=10&type=Repositories`)
  const data= await res.json()
  console.log(data)
  return {
    props: {data}, 
  }

}


export default Projects;

